## 1. Data Loading and Initial Inspection

I will start by loading all four provided CSV files (`aqi.csv`, `idsp.csv`, `population_projection.csv`, `vahan.csv`) into pandas DataFrames. Then, I will display the first few rows and a summary of each DataFrame to understand their structure and content.

In [21]:
import pandas as pd

# Load the datasets
aqi_df = pd.read_csv('/content/aqi.csv')
idsp_df = pd.read_csv('/content/idsp.csv', encoding='latin1') # Added encoding
population_df = pd.read_csv('/content/population_projection.csv')
vahan_df = pd.read_csv('/content/vahan.csv')

print("AQI Data (aqi_df):")
display(aqi_df.head())
print("\nAQI Data Info:")
aqi_df.info()

print("\nIDSP Data (idsp_df):")
display(idsp_df.head())
print("\nIDSP Data Info:")
idsp_df.info()

print("\nPopulation Projection Data (population_df):")
display(population_df.head())
print("\nPopulation Projection Data Info:")
population_df.info()

print("\nVahan Data (vahan_df):")
display(vahan_df.head())
print("\nVahan Data Info:")
vahan_df.info()

AQI Data (aqi_df):

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,note
0,30-04-2025,Maharashtra,Amravati,2,PM10,78,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
1,30-04-2025,Bihar,Purnia,1,CO,56,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
2,30-04-2025,Madhya Pradesh,Katni,1,O3,98,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
3,30-04-2025,Chhattisgarh,Tumidih,1,PM10,103,Moderate,number_of_monitoring_stations in Absolute Numb...,NaN
4,30-04-2025,Assam,Byrnihat,1,PM2.5,61,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN

AQI Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235785 entries, 0 to 235784
Data columns (total 9 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   date                           235785 non-null  object
 1   state                          235785 non-null  object
 2   area                           235785 non-null  object
 3   number_of_monitoring_stations  235785 non-null  int64
 4   prominent_pollutants           235785 non-null  object
 5   aqi_value                      235785 non-null  int64
 6   air_quality_status             235785 non-null  object
 7   unit                           235785 non-null  object
 8   note                           0 non-null       float64
dtypes: float64(1), int64(2), object(6)
memory usage: 16.2+ MB

IDSP Data (idsp_df):

,year,week,outbreak_starting_date,reporting_date,state,district,disease_illness_name,status,cases,deaths,unit,note
0,2025,16,15-04-2025,15-04-2025,Andhra Pradesh,Kakinada,Acute Diarrheal Disease,Reported,22,0,"cases in absolute number, deaths in absolute n...",NaN
1,2025,16,15-04-2025,17-04-2025,Assam,Biswanath,Chickenpox,Reported,1,1,"cases in absolute number, deaths in absolute n...",NaN
2,2025,16,19-04-2025,20-04-2025,Assam,Dhemaji,Food Poisoning,Reported,16,0,"cases in absolute number, deaths in absolute n...",NaN
3,2025,16,19-04-2025,19-04-2025,Bihar,Gopalganj,Fever with Rash,Reported,5,0,"cases in absolute number, deaths in absolute n...",NaN
4,2025,16,12-04-2025,15-04-2025,Bihar,Madhubani,Acute Diarrheal Disease,Reported,21,0,"cases in absolute number, deaths in absolute n...",NaN

IDSP Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6474 entries, 0 to 6473
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    6474 non-null   int64
 1   week                    6474 non-null   int64
 2   outbreak_starting_date  6474 non-null   object
 3   reporting_date          5455 non-null   object
 4   state                   6474 non-null   object
 5   district                6473 non-null   object
 6   disease_illness_name    6469 non-null   object
 7   status                  6474 non-null   object
 8   cases                   6474 non-null   int64
 9   deaths                  6474 non-null   int64
 10  unit                    6474 non-null   object
 11  note                    6 non-null      object
dtypes: int64(4), object(8)
memory usage: 607.1+ KB

Population Projection Data (population_df):

   year    month        state  gender  value                unit  note
0  2036  October  West Bengal   Total  43964  value in Thousands   NaN
1  2036  October  West Bengal    Male  22615  value in Thousands   NaN
2  2036  October  West Bengal  Female  21349  value in Thousands   NaN
3  2036  October  Uttarakhand   Total   5506  value in Thousands   NaN
4  2036  October  Uttarakhand    Male   2922  value in Thousands   NaN

Population Projection Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8892 entries, 0 to 8891
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    8892 non-null   int64
 1   month   8892 non-null   object
 2   state   8892 non-null   object
 3   gender  8892 non-null   object
 4   value   8892 non-null   int64
 5   unit    8892 non-null   object
 6   note    0 non-null      float64
dtypes: float64(1), int64(2), object(4)
memory usage: 486.4+ KB

Vahan Data (vahan_df):

,year,month,state,rto,vehicle_class,fuel,value,unit,note
0,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,BUS,DIESEL,2,value in Absolute Number,NaN
1,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,GOODS CARRIER,DIESEL,23,value in Absolute Number,NaN
2,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,GOODS CARRIER,PETROL,1,value in Absolute Number,NaN
3,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,M-CYCLE/SCOOTER,ELECTRIC(BOV),1,value in Absolute Number,NaN
4,2025,April,Andaman and Nicobar Islands,All Vahan Running Office,M-CYCLE/SCOOTER,PETROL,387,value in Absolute Number,NaN

Vahan Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64841 entries, 0 to 64840
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           64841 non-null  int64
 1   month          64841 non-null  object
 2   state          64841 non-null  object
 3   rto            64841 non-null  object
 4   vehicle_class  64841 non-null  object
 5   fuel           64841 non-null  object
 6   value          64841 non-null  int64
 7   unit           64841 non-null  object
 8   note           0 non-null      float64
dtypes: float64(1), int64(2), object(6)
memory usage: 4.5+ MB

## Addressing Question 1: Top 5 and bottom 5 areas with highest average AQI

**Question 1**: Top 5 and bottom 5 areas with highest average AQI (considering areas with data covering Dec 2024 → May 2025, i.e., last 6 months).

To answer this, I will perform the following steps:
1.  Convert the 'Date' column in `aqi_df` to datetime objects.
2.  Filter the data to include only the period from December 2024 to May 2025.
3.  Calculate the average AQI for each 'Area' within this filtered period.
4.  Identify the top 5 and bottom 5 areas based on their average AQI.

In [22]:
# Convert 'date' column to datetime objects (corrected column name and added format to suppress warning)
aqi_df['date'] = pd.to_datetime(aqi_df['date'], format='%d-%m-%Y')

# Define the date range for filtering (Dec 2024 to May 2025)
start_date = pd.to_datetime('2024-12-01')
end_date = pd.to_datetime('2025-05-31')

# Filter data for the specified period
filtered_aqi_q1 = aqi_df[(aqi_df['date'] >= start_date) & (aqi_df['date'] <= end_date)]

# Calculate average AQI for each area (corrected 'Area' to 'area' and 'AQI' to 'aqi_value')
average_aqi_by_area = filtered_aqi_q1.groupby('area')['aqi_value'].mean().sort_values(ascending=False)

# Get top 5 areas with highest average AQI
top_5_areas = average_aqi_by_area.head(5)

# Get bottom 5 areas with lowest average AQI
bottom_5_areas = average_aqi_by_area.tail(5)

print("Top 5 Areas with Highest Average AQI (Dec 2024 - May 2025):")
display(top_5_areas)

print("\nBottom 5 Areas with Lowest Average AQI (Dec 2024 - May 2025):")
display(bottom_5_areas)

Top 5 Areas with Highest Average AQI (Dec 2024 - May 2025):

area
Byrnihat       284.194915
Delhi          238.920000
Hajipur        233.666667
Bahadurgarh    226.437500
Gurugram       204.143836
Name: aqi_value, dtype: float64

Bottom 5 Areas with Lowest Average AQI (Dec 2024 - May 2025):

area
Chamarajanagar    44.807692
Vijayapura        44.328767
Madikeri          42.951049
Palkalaiperur     42.794872
Tirunelveli       33.310078
Name: aqi_value, dtype: float64

## Addressing Question 2: Top 2 and bottom 2 prominent pollutants for each state of Southern India

**Question 2**: Top 2 and bottom 2 prominent pollutants for each state of Southern India (states = Andhra Pradesh, Telangana, Karnataka, Kerala, Tamil Nadu; consider 2022 onward).

To answer this, I will perform the following steps:
1.  Define the list of Southern Indian states.
2.  Filter the `aqi_df` for these states and for dates from 2022 onwards.
3.  Identify prominent pollutants from the available columns.
4.  For each state, calculate the average concentration of each pollutant.
5.  Determine the top 2 and bottom 2 pollutants based on their average concentrations for each state.

In [23]:
# 1. Define Southern Indian states
southern_states = [
    'Andhra Pradesh',
    'Telangana',
    'Karnataka',
    'Kerala',
    'Tamil Nadu'
]

# 2. Filter data for southern states and from 2022 onwards
start_date_q2 = pd.to_datetime('2022-01-01')
filtered_aqi_q2 = aqi_df[
    (aqi_df['state'].isin(southern_states)) &
    (aqi_df['date'] >= start_date_q2)
].copy()

# 3. Analyze prominent pollutants by counting their occurrences
# Group by state and count the occurrences of each prominent_pollutants
pollutant_counts_by_state = filtered_aqi_q2.groupby(['state', 'prominent_pollutants']).size().unstack(fill_value=0)

print("Count of Prominent Pollutants by Southern Indian State (from 2022):")
display(pollutant_counts_by_state)

# 4. Determine top 2 and bottom 2 prominent pollutants for each state
prominent_pollutants_results = {}

for state in southern_states:
    if state in pollutant_counts_by_state.index:
        state_pollutants = pollutant_counts_by_state.loc[state]
        # Sort pollutants by count
        sorted_pollutants = state_pollutants.sort_values(ascending=False)

        # Get top 2 (if available)
        top_2 = sorted_pollutants.head(2).index.tolist()

        # Get bottom 2 (if available, and ensuring they are not the same as top 2 if there are few pollutants)
        # This logic needs to be robust for cases with few distinct pollutants or all having the same count
        bottom_2_candidates = sorted_pollutants.tail(2).index.tolist()

        # Filter out pollutants that are already in top_2 if there are more than 2 distinct pollutants
        # And ensure we don't pick the same pollutant for both top and bottom if there's only one type
        if len(sorted_pollutants) > 2:
            temp_bottom = [p for p in bottom_2_candidates if p not in top_2]
            # If temp_bottom is empty, it means top_2 and bottom_2_candidates overlap completely or are the same.
            # In this case, we might need to adjust or simply not report bottom 2 if there isn't clear distinction.
            if len(temp_bottom) == 0 and len(sorted_pollutants) > 0:
                # If all pollutants have the same count, then there's no clear 'bottom'
                if len(set(sorted_pollutants.values)) == 1:
                    bottom_2 = [] # No distinct bottom if all are same
                else:
                    # Try to get the next distinct values from bottom if possible
                    unique_values = sorted_pollutants.unique()
                    if len(unique_values) > 1:
                        second_last_val = unique_values[-2]
                        bottom_2 = sorted_pollutants[sorted_pollutants == second_last_val].index.tolist()
                        if len(bottom_2) > 2:
                            bottom_2 = bottom_2[-2:] # Take last two if many have the same second lowest
                        elif len(bottom_2) == 1 and len(unique_values) > 2: # If only one at second lowest, try third lowest
                            third_last_val = unique_values[-3]
                            bottom_2.extend(sorted_pollutants[sorted_pollutants == third_last_val].index.tolist()[:1])
                    else: # All counts are identical
                        bottom_2 = []
            else:
                bottom_2 = temp_bottom
                if len(bottom_2) < 2 and len(sorted_pollutants) > len(top_2):
                    # If after removing top_2, we still need more for bottom_2, add from the remaining unique lowest ones
                    remaining_pollutants = sorted_pollutants[~sorted_pollutants.index.isin(top_2)].tail(2).index.tolist()
                    for p in remaining_pollutants:
                        if p not in bottom_2:
                            bottom_2.append(p)
                    bottom_2 = bottom_2[-2:] # Ensure only up to 2 are kept

        elif len(sorted_pollutants) <= 2: # If 2 or fewer distinct pollutants, top and bottom might be the same or one
            if len(sorted_pollutants) == 1:
                bottom_2 = [] # Only one pollutant, no distinct bottom
            else:
                if sorted_pollutants.iloc[0] == sorted_pollutants.iloc[1]:
                    bottom_2 = [] # Both are equally prominent, no distinct bottom
                else:
                    bottom_2 = sorted_pollutants.tail(1).index.tolist() # Only one bottom pollutant
        else:
            bottom_2 = sorted_pollutants.tail(2).index.tolist()

        prominent_pollutants_results[state] = {
            'Top 2 Prominent Pollutants (by frequency)': top_2,
            'Bottom 2 Prominent Pollutants (by frequency)': bottom_2
        }
    else:
        prominent_pollutants_results[state] = {
            'Top 2 Prominent Pollutants (by frequency)': 'No data',
            'Bottom 2 Prominent Pollutants (by frequency)': 'No data'
        }

print("\nTop 2 and Bottom 2 Prominent Pollutants for each Southern Indian State (by frequency of occurrence):")
for state, pollutants in prominent_pollutants_results.items():
    print(f"\nState: {state}")
    print(f"  Top 2: {', '.join(pollutants['Top 2 Prominent Pollutants (by frequency)'] )}")
    print(f"  Bottom 2: {', '.join(pollutants['Bottom 2 Prominent Pollutants (by frequency)'] )}")

Count of Prominent Pollutants by Southern Indian State (from 2022):

prominent_pollutants,CO,"CO,NO2","CO,O3","CO,SO2",NH3,NO2,"NO2,O3","NO2,PM10,CO","NO2,SO2","NO2,SO2,CO",...,"PM2.5,CO,SO2","PM2.5,NH3","PM2.5,NH3,CO","PM2.5,NO2","PM2.5,O3","PM2.5,PM10","PM2.5,PM10,CO","PM2.5,SO2",SO2,"SO2,O3"
state,,,,,,,,,,,,,,,,,,,,,
Andhra Pradesh,520,25,7,0,0,139,8,0,0,0,...,0,0,0,59,65,333,0,0,11,0
Karnataka,2913,5,18,24,33,364,1,12,0,1,...,0,0,0,1,74,440,71,0,648,1
Kerala,699,26,6,0,10,54,0,0,0,0,...,0,0,0,0,61,160,0,0,7,0
Tamil Nadu,797,32,33,15,4,380,16,5,2,0,...,2,5,1,24,91,469,120,7,787,0
Telangana,0,2,1,0,0,1,0,27,0,0,...,0,0,0,1,32,343,73,0,0,0

Top 2 and Bottom 2 Prominent Pollutants for each Southern Indian State (by frequency of occurrence):

State: Andhra Pradesh
  Top 2: PM10, PM2.5
  Bottom 2: PM2.5,SO2, SO2,O3

State: Telangana
  Top 2: PM2.5,PM10, PM10
  Bottom 2: SO2, SO2,O3

State: Karnataka
  Top 2: PM10, CO
  Bottom 2: PM2.5,NH3,CO, PM2.5,SO2

State: Kerala
  Top 2: PM10, PM2.5
  Bottom 2: PM2.5,SO2, SO2,O3

State: Tamil Nadu
  Top 2: PM10, PM2.5
  Bottom 2: PM10,PM2.5,SO2, SO2,O3

## Addressing Question 3: AQI values on weekends vs weekdays in Indian metro cities

**Question 3**: Do AQI values improve on weekends vs weekdays in Indian metro cities: Delhi, Mumbai, Chennai, Kolkata, Bengaluru, Hyderabad, Ahmedabad, Pune (use data from last 1 year from run date — code uses 365 days prior to the max date in the AQI file).

To answer this, I will perform the following steps:
1.  Define the list of target metro cities.
2.  Determine the latest date in the `aqi_df` to establish the 'run date'.
3.  Filter the `aqi_df` for the last 365 days leading up to the max date and for the specified metro cities.
4.  Extract the day of the week for each entry and categorize them as 'Weekday' or 'Weekend'.
5.  Calculate the average AQI for weekdays and weekends for each city.
6.  Compare and present the results to see if AQI values generally improve (i.e., decrease) on weekends.

In [24]:
import numpy as np

# 1. Define target metro cities
metro_cities = [
    'Delhi',
    'Mumbai',
    'Chennai',
    'Kolkata',
    'Bengaluru',
    'Hyderabad',
    'Ahmedabad',
    'Pune'
]

# Ensure 'area' column is used for filtering city names
# Make city names consistent if needed, assuming 'area' contains city names

# 2. Determine the latest date in the aqi_df
max_date_aqi = aqi_df['date'].max()

# 3. Filter data for the last 365 days and for metro cities
start_date_q3 = max_date_aqi - pd.Timedelta(days=365)
filtered_aqi_q3 = aqi_df[
    (aqi_df['date'] >= start_date_q3) &
    (aqi_df['date'] <= max_date_aqi) &
    (aqi_df['area'].str.contains('|'.join(metro_cities), case=False, na=False)) # Case-insensitive search for cities within area names
].copy()

# Map common city names to standardized metro_cities list for consistency
def standardize_city_name(area_name, metro_cities_list):
    for city in metro_cities_list:
        if city.lower() in area_name.lower():
            return city
    return area_name # Return original if no match

filtered_aqi_q3['city'] = filtered_aqi_q3['area'].apply(lambda x: standardize_city_name(x, metro_cities))
filtered_aqi_q3 = filtered_aqi_q3[filtered_aqi_q3['city'].isin(metro_cities)] # Filter to only exact metro cities

# 4. Extract day of the week and categorize as 'Weekday' or 'Weekend'
# Monday=0, Sunday=6
filtered_aqi_q3['day_of_week'] = filtered_aqi_q3['date'].dt.dayofweek
filtered_aqi_q3['day_type'] = np.where(
    filtered_aqi_q3['day_of_week'].isin([5, 6]), # 5 is Saturday, 6 is Sunday
    'Weekend',
    'Weekday'
)

# 5. Calculate average AQI for weekdays and weekends for each city
aqi_weekday_weekend = filtered_aqi_q3.groupby(['city', 'day_type'])['aqi_value'].mean().unstack()

print("Average AQI on Weekdays vs. Weekends for Indian Metro Cities (Last 1 Year):")
display(aqi_weekday_weekend)

# 6. Compare AQI values and determine if they improve on weekends
aqi_weekday_weekend['Improvement_on_Weekend'] = aqi_weekday_weekend['Weekday'] > aqi_weekday_weekend['Weekend']

print("\nAQI Improvement on Weekends (lower AQI on Weekend is an improvement):")
display(aqi_weekday_weekend[['Weekday', 'Weekend', 'Improvement_on_Weekend']])

Average AQI on Weekdays vs. Weekends for Indian Metro Cities (Last 1 Year):

day_type      Weekday     Weekend
city
Ahmedabad  114.716475  116.038462
Bengaluru   71.896552   72.384615
Chennai     71.245211   68.442308
Delhi      208.697318  198.923077
Hyderabad   77.923372   79.009615
Kolkata     91.727969   91.259615
Mumbai      94.454023   95.451923
Pune       101.954023  100.846154

AQI Improvement on Weekends (lower AQI on Weekend is an improvement):

day_type      Weekday     Weekend  Improvement_on_Weekend
city
Ahmedabad  114.716475  116.038462                   False
Bengaluru   71.896552   72.384615                   False
Chennai     71.245211   68.442308                    True
Delhi      208.697318  198.923077                    True
Hyderabad   77.923372   79.009615                   False
Kolkata     91.727969   91.259615                    True
Mumbai      94.454023   95.451923                   False
Pune       101.954023  100.846154                    True

## Addressing Question 5: Air quality categories for Bengaluru

**Question 5**: For Bengaluru, how many days fell under each air quality category (Good, Moderate, Poor, etc.) between March 1, 2025 — May 31, 2025.

To answer this, I will perform the following steps:
1.  Filter `aqi_df` for 'Bengaluru' as the area and the specified date range (March 1, 2025 – May 31, 2025).
2.  Count the occurrences of each `air_quality_status` category within the filtered data.
3.  Present the counts for each category.

In [25]:
# Define the city and date range for filtering
target_city_q5 = 'Bengaluru'
start_date_q5 = pd.to_datetime('2025-03-01')
end_date_q5 = pd.to_datetime('2025-05-31')

# Filter aqi_df for Bengaluru within the specified date range
filtered_aqi_bengaluru = aqi_df[
    (aqi_df['area'] == target_city_q5) &
    (aqi_df['date'] >= start_date_q5) &
    (aqi_df['date'] <= end_date_q5)
].copy()

# Count the occurrences of each air_quality_status category
air_quality_category_counts = filtered_aqi_bengaluru['air_quality_status'].value_counts()

print(f"Air Quality Category Counts for {target_city_q5} (March 1, 2025 - May 31, 2025):")
display(air_quality_category_counts)

Air Quality Category Counts for Bengaluru (March 1, 2025 - May 31, 2025):

air_quality_status
Satisfactory    48
Moderate        13
Name: count, dtype: int64

## Addressing Question 6: Severity Mapping - Persistent or Worsening AQI

**Question 6**: Severity Mapping: identify cities with persistent or worsening AQI (trend analysis & count of days in "Unhealthy" categories).

To answer this, I will perform the following steps:
1.  Define 'Unhealthy' AQI categories based on `air_quality_status` (e.g., 'Poor', 'Very Poor', 'Severe').
2.  Calculate the number of days each city spent in these 'Unhealthy' categories.
3.  Perform a simple trend analysis by comparing the number of 'Unhealthy' days in two consecutive periods (e.g., last 6 months vs. prior 6 months, or year-over-year comparison).
4.  Identify cities that show an increasing trend in 'Unhealthy' days or consistently high counts.

For simplicity and to demonstrate a trend, I'll compare the count of 'Unhealthy' days in the last 6 months of data with the preceding 6 months. I'll also consider cities with a high total count of 'Unhealthy' days.

In [26]:
# 1. Define 'Unhealthy' AQI categories
unhealthy_categories = ['Poor', 'Very Poor', 'Severe', 'Critical', 'Hazardous'] # Add categories as per AQI standards if available

# Filter AQI data to only include 'Unhealthy' days
unhealthy_aqi_df = aqi_df[aqi_df['air_quality_status'].isin(unhealthy_categories)].copy()

# 2. Get the latest date in the dataset for a relevant period comparison
max_date = aqi_df['date'].max()

# Define comparison periods: Last 6 months vs. Prior 6 months
end_period_1 = max_date
start_period_1 = max_date - pd.Timedelta(days=180) # Last 6 months

end_period_2 = start_period_1 - pd.Timedelta(days=1) # Day before start_period_1
start_period_2 = end_period_2 - pd.Timedelta(days=180) # Prior 6 months

# Filter unhealthy data for Period 1 (Last 6 months)
unhealthy_period_1 = unhealthy_aqi_df[
    (unhealthy_aqi_df['date'] >= start_period_1) &
    (unhealthy_aqi_df['date'] <= end_period_1)
]

# Filter unhealthy data for Period 2 (Prior 6 months)
unhealthy_period_2 = unhealthy_aqi_df[
    (unhealthy_aqi_df['date'] >= start_period_2) &
    (unhealthy_aqi_df['date'] <= end_period_2)
]

# Count unhealthy days per city for each period
counts_period_1 = unhealthy_period_1.groupby('area').size().rename('Unhealthy_Days_Last_6_Months')
counts_period_2 = unhealthy_period_2.groupby('area').size().rename('Unhealthy_Days_Prior_6_Months')

# Combine counts for comparison
severity_mapping = pd.concat([counts_period_1, counts_period_2], axis=1).fillna(0)

# Calculate the change in unhealthy days
severity_mapping['Change_Unhealthy_Days'] = severity_mapping['Unhealthy_Days_Last_6_Months'] - severity_mapping['Unhealthy_Days_Prior_6_Months']

# Identify cities with worsening AQI (increased unhealthy days)
worsening_cities = severity_mapping[severity_mapping['Change_Unhealthy_Days'] > 0].sort_values(by='Change_Unhealthy_Days', ascending=False)

# Identify cities with persistently high unhealthy AQI (e.g., top 10 by total unhealthy days in last period)
persistent_unhealthy_cities = severity_mapping.sort_values(by='Unhealthy_Days_Last_6_Months', ascending=False).head(10)

print(f"Cities with a worsening trend in Unhealthy AQI (comparing last 6 months to prior 6 months, periods ending {max_date.strftime('%Y-%m-%d')} and {end_period_2.strftime('%Y-%m-%d')} respectively):\n")
display(worsening_cities)

print(f"\nCities with persistently high Unhealthy AQI (Top 10 by count of unhealthy days in the last 6 months ending {max_date.strftime('%Y-%m-%d')}):\n")
display(persistent_unhealthy_cities)

Cities with a worsening trend in Unhealthy AQI (comparing last 6 months to prior 6 months, periods ending 2025-04-30 and 2024-10-31 respectively):

,Unhealthy_Days_Last_6_Months,Unhealthy_Days_Prior_6_Months,Change_Unhealthy_Days
area,,,
Hajipur,116.0,19.0,97.0
Patna,102.0,16.0,86.0
Talcher,82.0,0.0,82.0
Howrah,80.0,0.0,80.0
Delhi,126.0,46.0,80.0
...,...,...,...
Prayagraj,1.0,0.0,1.0
Rupnagar,9.0,8.0,1.0
Pudukottai,1.0,0.0,1.0
Tiruchirappalli,1.0,0.0,1.0
Vellore,1.0,0.0,1.0

Cities with persistently high Unhealthy AQI (Top 10 by count of unhealthy days in the last 6 months ending 2025-04-30):

,Unhealthy_Days_Last_6_Months,Unhealthy_Days_Prior_6_Months,Change_Unhealthy_Days
area,,,
Delhi,126.0,46.0,80.0
Byrnihat,120.0,47.0,73.0
Hajipur,116.0,19.0,97.0
Gurugram,103.0,36.0,67.0
Patna,102.0,16.0,86.0
Ghaziabad,95.0,41.0,54.0
Durgapur,87.0,8.0,79.0
Asansol,85.0,9.0,76.0
Talcher,82.0,0.0,82.0
Howrah,80.0,0.0,80.0

## Addressing Question 7: Health Impact Correlation

**Question 7**: Correlate AQI spikes with health event counts from idsp (e.g., respiratory/ARI/diarrheal?) — produce aggregated correlation measures per state/month.

To answer this, I will perform the following steps:
1.  Process `idsp_df`:
    *   Convert date columns to datetime objects.
    *   Extract 'year' and 'month'.
    *   Filter for specified health events (Acute Diarrheal Disease, Acute Respiratory Infection, Pneumonia, etc.).
    *   Aggregate `cases` per state, year, and month.
2.  Process `aqi_df`:
    *   Ensure 'date' column is datetime.
    *   Extract 'year' and 'month'.
    *   Aggregate `aqi_value` (e.g., mean) per state, year, and month.
3.  Merge Data: Combine the aggregated `aqi_df` and `idsp_df` on 'state', 'year', and 'month'.
4.  Calculate Correlation: Compute the correlation between AQI and health event counts for each state.

In [27]:
# 1. Process idsp_df
# Convert date column to datetime objects (handling potential multiple date formats)
# Using 'reporting_date' as it's more direct for health events
idsp_df['reporting_date'] = pd.to_datetime(idsp_df['reporting_date'], errors='coerce', dayfirst=True)

# Drop rows where date conversion failed
idsp_df_cleaned = idsp_df.dropna(subset=['reporting_date']).copy()

idsp_df_cleaned['year'] = idsp_df_cleaned['reporting_date'].dt.year
idsp_df_cleaned['month'] = idsp_df_cleaned['reporting_date'].dt.month

# Define target health events (assuming these are the relevant ones from the dataset)
target_diseases = [
    'Acute Diarrheal Disease',
    'Acute Respiratory Infection',
    'Pneumonia',
    'Influenza',
    'Bronchitis',
    'Asthma',
    'Cholera',
    'Typhoid'
]

filtered_idsp_q7 = idsp_df_cleaned[idsp_df_cleaned['disease_illness_name'].isin(target_diseases)]

# Aggregate cases per state, year, and month
aggregated_idsp_q7 = filtered_idsp_q7.groupby(['state', 'year', 'month'])['cases'].sum().reset_index()
aggregated_idsp_q7.rename(columns={'cases': 'total_health_cases'}, inplace=True)

print("Aggregated Health Cases (IDSP data per state/year/month):")
display(aggregated_idsp_q7.head())

# 2. Process aqi_df
# 'date' column is already datetime from previous steps and format='%d-%m-%Y'
aqi_df['year'] = aqi_df['date'].dt.year
aqi_df['month'] = aqi_df['date'].dt.month

# Aggregate mean AQI per state, year, and month
aggregated_aqi_q7 = aqi_df.groupby(['state', 'year', 'month'])['aqi_value'].mean().reset_index()
aggregated_aqi_q7.rename(columns={'aqi_value': 'mean_aqi'}, inplace=True)

print("\nAggregated Mean AQI (per state/year/month):")
display(aggregated_aqi_q7.head())

# 3. Merge Data
merged_data_q7 = pd.merge(
    aggregated_aqi_q7,
    aggregated_idsp_q7,
    on=['state', 'year', 'month'],
    how='inner' # Use inner join to only include periods where both AQI and health data exist
)

print("\nMerged AQI and Health Data (first 5 rows):")
display(merged_data_q7.head())

# 4. Calculate Correlation
# Calculate correlation for each state between mean_aqi and total_health_cases
correlation_by_state = merged_data_q7.groupby('state').apply(
    lambda x: x['mean_aqi'].corr(x['total_health_cases'])
)

correlation_by_state = correlation_by_state.rename('AQI_Health_Correlation').dropna()

print("\nCorrelation between Mean AQI and Total Health Cases per State:")
display(correlation_by_state.sort_values(ascending=False))

Aggregated Health Cases (IDSP data per state/year/month):

                         state  year  month  total_health_cases
0  Andaman and Nicobar Islands  2022      9                  23
1  Andaman and Nicobar Islands  2023      8                  18
2  Andaman and Nicobar Islands  2024      6                  76
3               Andhra Pradesh  2022      5                  59
4               Andhra Pradesh  2023      3                  22

Aggregated Mean AQI (per state/year/month):

                         state  year  month   mean_aqi
0  Andaman and Nicobar Islands  2025      2  67.285714
1  Andaman and Nicobar Islands  2025      3  66.920000
2  Andaman and Nicobar Islands  2025      4  46.269231
3               Andhra Pradesh  2022      4  54.445378
4               Andhra Pradesh  2022      5  73.534483

Merged AQI and Health Data (first 5 rows):

            state  year  month   mean_aqi  total_health_cases
0  Andhra Pradesh  2022      5  73.534483                  59
1  Andhra Pradesh  2023      3  94.272727                  22
2  Andhra Pradesh  2023      6  64.911894                  54
3  Andhra Pradesh  2023      7  43.792271                  27
4  Andhra Pradesh  2023      9  50.030000                 297

Correlation between Mean AQI and Total Health Cases per State:

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2914: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/tmp/ipykernel_3606/823589696.py:58: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  correlation_by_state = merged_data_q7.groupby('state').apply(

state
Mizoram              0.549877
Kerala               0.295525
Arunachal Pradesh    0.159775
Odisha               0.125592
West Bengal         -0.006708
Maharashtra         -0.065813
Haryana             -0.119733
Himachal Pradesh    -0.121617
Puducherry          -0.125915
Jharkhand           -0.162249
Rajasthan           -0.196423
Assam               -0.230529
Gujarat             -0.258025
Tamil Nadu          -0.301548
Telangana           -0.318325
Uttar Pradesh       -0.322123
Punjab              -0.355890
Karnataka           -0.363453
Jammu and Kashmir   -0.413106
Uttarakhand         -0.432556
Madhya Pradesh      -0.443845
Chhattisgarh        -0.473344
Andhra Pradesh      -0.512568
Nagaland            -0.570248
Bihar               -0.643999
Meghalaya           -0.715434
Tripura             -0.856982
Manipur             -0.960180
Name: AQI_Health_Correlation, dtype: float64

## Addressing Question 8: Demand Triggers - AQI Spikes and Inferred Demand

**Question 8**: Demand Triggers: analyze temporal relationship between pollution spikes (AQI) and inferred demand triggers (proxy: spikes in AQI correlated with news/health events or vehicle counts growth; we’ll show an approach using vehicle registrations & population as proxy for potential market).

This question is multifaceted. Given the available datasets, I will focus on correlating AQI with vehicle counts (from `vahan_df`) and possibly health events (from `idsp_df`) as proxies for demand triggers, aggregated at a state and monthly level.

To answer this, I will perform the following steps:
1.  Process `vahan_df`:
    *   Clean and convert date columns.
    *   Aggregate `total_vehicles` per state, year, and month.
2.  Re-use `aggregated_aqi_q7` (mean AQI per state, year, month) from Question 7.
3.  Merge `aggregated_aqi_q7` with aggregated `vahan_df` on state, year, and month.
4.  Calculate correlation between AQI and vehicle counts for each state.
5.  Optionally, correlate AQI with health events (`aggregated_idsp_q7`) at a state/month level for additional insights into demand triggers.

In [28]:
import pandas as pd

# 1. Process vahan_df
# Ensure 'year' and 'month' columns are available and correctly formatted

vahan_df_cleaned = vahan_df.copy()

# First, create a temporary date string from 'year' and 'month' (e.g., '2022-April-01')
vahan_df_cleaned['temp_date'] = vahan_df_cleaned['year'].astype(str) + '-' + vahan_df_cleaned['month'] + '-01'
# Convert to datetime objects and then extract month as integer
vahan_df_cleaned['month_num'] = pd.to_datetime(vahan_df_cleaned['temp_date']).dt.month

# Aggregate total_vehicles per state, year, and numerical month
aggregated_vahan_q8 = vahan_df_cleaned.groupby(['state', 'year', 'month_num'])['value'].sum().reset_index()
aggregated_vahan_q8.rename(columns={'value': 'total_vehicle_registrations', 'month_num': 'month'}, inplace=True)

print("Aggregated Vehicle Registrations (Vahan data per state/year/month):")
display(aggregated_vahan_q8.head())

# 2. Re-use aggregated_aqi_q7 from Question 7
# 'aggregated_aqi_q7' is already computed: mean_aqi per state, year, month

# 3. Merge aggregated_aqi_q7 with aggregated_vahan_q8
merged_data_q8_vahan = pd.merge(
    aggregated_aqi_q7,
    aggregated_vahan_q8,
    on=['state', 'year', 'month'],
    how='inner'
)

print("\nMerged AQI and Vehicle Registrations Data (first 5 rows):")
display(merged_data_q8_vahan.head())

# 4. Calculate correlation between AQI and vehicle counts
correlation_aqi_vahan_by_state = merged_data_q8_vahan.groupby('state').apply(
    lambda x: x['mean_aqi'].corr(x['total_vehicle_registrations'])
)

correlation_aqi_vahan_by_state = correlation_aqi_vahan_by_state.rename('AQI_Vehicle_Correlation').dropna()

print("\nCorrelation between Mean AQI and Total Vehicle Registrations per State:")
display(correlation_aqi_vahan_by_state.sort_values(ascending=False))

# 5. Optional: Correlate AQI with health events for additional insights (re-using aggregated_idsp_q7)
merged_data_q8_health = pd.merge(
    aggregated_aqi_q7,
    aggregated_idsp_q7,
    on=['state', 'year', 'month'],
    how='inner'
)

correlation_aqi_health_by_state = merged_data_q8_health.groupby('state').apply(
    lambda x: x['mean_aqi'].corr(x['total_health_cases'])
)

correlation_aqi_health_by_state = correlation_aqi_health_by_state.rename('AQI_Health_Correlation_Q8').dropna()

print("\n(Re-calculated) Correlation between Mean AQI and Total Health Cases per State (as a demand trigger proxy):\n(Note: This is similar to Q7, but included here for completeness of demand triggers analysis.)")
display(correlation_aqi_health_by_state.sort_values(ascending=False))

Aggregated Vehicle Registrations (Vahan data per state/year/month):

                         state  year  month  total_vehicle_registrations
0  Andaman and Nicobar Islands  2022      4                          614
1  Andaman and Nicobar Islands  2022      5                          511
2  Andaman and Nicobar Islands  2022      6                          580
3  Andaman and Nicobar Islands  2022      7                          570
4  Andaman and Nicobar Islands  2022      8                          616

Merged AQI and Vehicle Registrations Data (first 5 rows):

,state,year,month,mean_aqi,total_vehicle_registrations
0,Andaman and Nicobar Islands,2025,2,67.285714,636
1,Andaman and Nicobar Islands,2025,3,66.920000,675
2,Andaman and Nicobar Islands,2025,4,46.269231,710
3,Andhra Pradesh,2022,4,54.445378,70441
4,Andhra Pradesh,2022,5,73.534483,62766

Correlation between Mean AQI and Total Vehicle Registrations per State:

/tmp/ipykernel_3606/1382494268.py:35: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  correlation_aqi_vahan_by_state = merged_data_q8_vahan.groupby('state').apply(

state
Uttar Pradesh                  0.547312
Madhya Pradesh                 0.479145
Assam                          0.457604
Chhattisgarh                   0.446321
Delhi                          0.443550
Punjab                         0.428818
Haryana                        0.417477
Maharashtra                    0.407056
Nagaland                       0.405898
Rajasthan                      0.405304
Himachal Pradesh               0.394536
Jharkhand                      0.293880
Odisha                         0.272564
West Bengal                    0.245760
Gujarat                        0.237099
Manipur                        0.219454
Uttarakhand                    0.211510
Andhra Pradesh                 0.187033
Jammu and Kashmir              0.151699
Tripura                        0.129786
Bihar                          0.128348
Karnataka                      0.124893
Arunachal Pradesh              0.123123
Meghalaya                      0.108780
Tamil Nadu                     0.107778
Puducherry                     0.028029
Mizoram                        0.019897
Kerala                        -0.122861
Chandigarh                    -0.158789
Sikkim                        -0.236553
Andaman and Nicobar Islands   -0.857916
Name: AQI_Vehicle_Correlation, dtype: float64

(Re-calculated) Correlation between Mean AQI and Total Health Cases per State (as a demand trigger proxy):
(Note: This is similar to Q7, but included here for completeness of demand triggers analysis.)

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2914: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/tmp/ipykernel_3606/1382494268.py:52: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  correlation_aqi_health_by_state = merged_data_q8_health.groupby('state').apply(

state
Mizoram              0.549877
Kerala               0.295525
Arunachal Pradesh    0.159775
Odisha               0.125592
West Bengal         -0.006708
Maharashtra         -0.065813
Haryana             -0.119733
Himachal Pradesh    -0.121617
Puducherry          -0.125915
Jharkhand           -0.162249
Rajasthan           -0.196423
Assam               -0.230529
Gujarat             -0.258025
Tamil Nadu          -0.301548
Telangana           -0.318325
Uttar Pradesh       -0.322123
Punjab              -0.355890
Karnataka           -0.363453
Jammu and Kashmir   -0.413106
Uttarakhand         -0.432556
Madhya Pradesh      -0.443845
Chhattisgarh        -0.473344
Andhra Pradesh      -0.512568
Nagaland            -0.570248
Bihar               -0.643999
Meghalaya           -0.715434
Tripura             -0.856982
Manipur             -0.960180
Name: AQI_Health_Correlation_Q8, dtype: float64

## Addressing Question 4: Worst air quality months across top states

**Question 4**: Which months consistently show the worst air quality across Indian states — consider the top 10 states with the highest number of distinct areas (i.e., states with many monitored areas).

To answer this, I will perform the following steps:
1.  Identify the top 10 states based on the number of distinct 'area' entries in `aqi_df`.
2.  Filter `aqi_df` for these top 10 states.
3.  Extract the 'month' from the 'date' column.
4.  Calculate the average AQI for each month within each of the top states.
5.  Identify the month(s) with the highest average AQI for each of these states, indicating the worst air quality.

In [29]:
# 1. Identify the top 10 states based on the number of distinct 'area' entries
state_area_counts = aqi_df.groupby('state')['area'].nunique().sort_values(ascending=False)
top_10_states = state_area_counts.head(10).index.tolist()

print(f"Top 10 States with the highest number of distinct monitoring areas: {top_10_states}")

# 2. Filter aqi_df for these top 10 states
filtered_aqi_q4 = aqi_df[aqi_df['state'].isin(top_10_states)].copy()

# 3. Extract the 'month' from the 'date' column
filtered_aqi_q4['month'] = filtered_aqi_q4['date'].dt.month

# 4. Calculate the average AQI for each month within each of the top states
average_aqi_by_state_month = filtered_aqi_q4.groupby(['state', 'month'])['aqi_value'].mean().unstack()

print("\nAverage AQI by State and Month (for top 10 states by monitoring areas):")
display(average_aqi_by_state_month)

# 5. Identify the month(s) with the highest average AQI for each state
worst_months_by_state = average_aqi_by_state_month.idxmax(axis=1)

# Map month numbers to month names for better readability
month_names = {
    1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June',
    7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'
}

worst_months_by_state_named = worst_months_by_state.map(month_names)

print("\nMonths with consistently worst air quality (highest average AQI) for top 10 states:")
display(worst_months_by_state_named)

Top 10 States with the highest number of distinct monitoring areas: ['Rajasthan', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Haryana', 'Bihar', 'Uttar Pradesh', 'Odisha', 'Madhya Pradesh', 'Andhra Pradesh']

Average AQI by State and Month (for top 10 states by monitoring areas):

month,1,2,3,4,5,6,7,8,9,10,11,12
state,,,,,,,,,,,,
Andhra Pradesh,114.737649,94.380878,78.550000,70.892958,68.958416,63.189036,49.711896,55.243542,52.958955,77.188870,95.251701,99.070376
Bihar,245.566933,188.382303,147.437164,161.410650,132.232305,123.321359,79.254185,80.333540,79.327788,120.325742,229.583671,251.805770
Haryana,182.050792,139.747529,112.129722,149.710837,156.457801,133.026441,74.865957,74.851646,83.641838,152.962347,239.460372,185.766558
Karnataka,76.635036,76.640530,72.725065,66.458566,60.230155,50.309524,44.985893,46.606011,44.729479,60.514046,74.961631,71.608737
Madhya Pradesh,141.350850,117.451668,105.421538,119.286068,115.482558,86.672552,56.905660,62.585992,66.296965,114.667181,164.537452,144.827096
Maharashtra,141.343519,128.360674,122.873333,104.357298,99.167772,70.243047,51.378101,53.914165,59.005450,108.852142,158.832972,138.706070
Odisha,193.607264,144.886029,137.725358,129.213609,98.807437,92.396848,57.656294,65.726879,61.353933,91.329870,153.506276,167.737196
Rajasthan,165.444795,131.830609,118.794163,132.306374,137.707441,110.339909,82.075490,79.335551,79.577607,120.966514,193.222376,176.341312
Tamil Nadu,90.175020,81.792769,69.804633,61.693431,61.287902,55.133333,56.132530,55.864598,50.645943,59.190476,71.841410,77.937148
Uttar Pradesh,160.450838,122.905455,108.840508,138.230803,135.872906,122.774498,63.495157,70.229745,77.506667,144.283196,200.607203,166.219945

Months with consistently worst air quality (highest average AQI) for top 10 states:

state
Andhra Pradesh     January
Bihar             December
Haryana           November
Karnataka         February
Madhya Pradesh    November
Maharashtra       November
Odisha             January
Rajasthan         November
Tamil Nadu         January
Uttar Pradesh     November
dtype: object

In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Addressing Question 9: Market Size Proxies

**Question 9**: Market size proxies: leveraging population and other relevant data (e.g., economic indicators like vehicle registrations, household income, urbanization rates) to estimate potential market size.

For this question, I will primarily use the `population_df` to establish a direct proxy for market size. A larger population in a given state generally indicates a larger potential market. I will process the population data to get total population by state and year.

If more granular data or other economic indicators (like per capita income or urbanization rates) were available, they could be integrated for a more sophisticated market sizing model. For now, we'll focus on population projections as a foundational proxy.

In [31]:
# 1. Process population_df
# Filter for 'Total' gender to get overall population counts
population_total_q9 = population_df[population_df['gender'] == 'Total'].copy()

# Ensure 'value' is numeric (it represents population in thousands)
population_total_q9['value'] = pd.to_numeric(population_total_q9['value'], errors='coerce')

# Drop any rows where value could not be converted
population_total_q9.dropna(subset=['value'], inplace=True)

# Aggregate population per state and year
# Summing `value` which is already 'in Thousands' to get total population in thousands
aggregated_population_q9 = population_total_q9.groupby(['state', 'year'])['value'].sum().reset_index()
aggregated_population_q9.rename(columns={'value': 'total_population_thousands'}, inplace=True)

print("Aggregated Total Population (in thousands) per State and Year:")
display(aggregated_population_q9.head())

# We can also look at the latest projected population to identify the largest markets by population.
latest_year = aggregated_population_q9['year'].max()
population_latest_year = aggregated_population_q9[aggregated_population_q9['year'] == latest_year]

largest_markets_by_population = population_latest_year.sort_values(by='total_population_thousands', ascending=False)

print(f"\nTop 10 Largest Potential Markets by Total Population (in thousands) for the latest available year ({latest_year}):")
display(largest_markets_by_population.head(10))

# Further analysis could involve merging this with AQI data to identify large markets with poor air quality.

Aggregated Total Population (in thousands) per State and Year:

       state  year  total_population_thousands
0  All India  2011                     1139671
1  All India  2012                     1167223
2  All India  2013                     1194897
3  All India  2014                     1222822
4  All India  2015                     1250986

Top 10 Largest Potential Markets by Total Population (in thousands) for the latest available year (2036):

              state  year  total_population_thousands
25        All India  2036                     1790693
597     Maharashtra  2036                      214330
935   Uttar Pradesh  2036                      201916
857      Tamil Nadu  2036                      139996
337         Gujarat  2036                      134835
987     West Bengal  2036                      131453
467       Karnataka  2036                      109976
493          Kerala  2036                      107336
571  Madhya Pradesh  2036                       89493
285           Delhi  2036                       80147